trigger:
- main

variables:
  azureServiceConnectionId: 'aefec5e6-8deb-46c7-aab5-9198d93191df'
  webAppName: ''  # <- pon tu nombre de Web App
  environmentName: 'surio'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: Default   # <-- tu agente self-hosted

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        # Activar virtualenv segÃºn OS
        if [ -f "antenv/bin/activate" ]; then
            source antenv/bin/activate
        else
            antenv\Scripts\activate
        fi
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install Python dependencies"

    - task: ArchiveFiles@2
      displayName: 'Archive project files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/project.zip'
        replaceExistingArchive: true
        contents: |
          **/*.py
          **/*.txt
          **/requirements.txt
          **/manage.py
          **/proyect/**
          !**/antenv/**
          !**/.git/**
          !**/__pycache__/**
          !**/bin/**
          !**/Lib/**

    - upload: '$(Build.ArtifactStagingDirectory)/project.zip'
      displayName: 'Upload artifact'
      artifact: drop

- stage: Deploy
  displayName: Deploy Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: Default

    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/project.zip'
