trigger:
- main

variables:
  azureServiceConnectionId: 'aefec5e6-8deb-46c7-aab5-9198d93191df'
  webAppName: 'ProyectIS2'
  environmentName: 'surio'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: Default  # tu agente self-hosted en Windows

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - powershell: |
        python -m venv antenv
        .\antenv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install Python dependencies"

    # Crear un ZIP solo con archivos necesarios para deploy
    - task: ArchiveFiles@2
      displayName: 'Archive deployment files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/deploy.zip'
        replaceExistingArchive: true
        contents: |
          **/*.py
          **/requirements.txt
          **/manage.py
          **/proyect/**
          !**/antenv/**
          !**/.git/**
          !**/__pycache__/**
          !**/bin/**
          !**/Lib/**
          !**/db.sqlite3
          !**/media/**
          !**/logs/**
        advancedCompression: true
        compressionLevel: '1'  # compresión mínima y rápida

    - publish: '$(Build.ArtifactStagingDirectory)/deploy.zip'
      artifact: drop
      displayName: 'Publish artifact'

- stage: Deploy
  displayName: Deploy Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: Default

    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/deploy.zip'
