trigger:
- main

variables:
  azureServiceConnectionId: 'aefec5e6-8deb-46c7-aab5-9198d93191df'
  webAppName: 'ProyectIS2'  # <- pon tu nombre de Web App
  environmentName: 'surio'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: Default   # <-- tu agente self-hosted en Windows

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - powershell: |
        python -m venv antenv
        .\antenv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install Python dependencies"

    # Copiar solo archivos necesarios a ArtifactStagingDirectory
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(projectRoot)'
        Contents: |
          **/*.py
          **/requirements.txt
          **/manage.py
          **/proyect/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: "Copy files for deployment"

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop
      displayName: 'Publish artifact'

- stage: Deploy
  displayName: Deploy Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: Default

    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop'
